modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
license = "Ultreon API 1.0"
issueTrackerURL = "https://github.com/Ultreon/advanced-debug/issues"

# The main mod, and all sub-mods.
[[mods]]
modId = "advanced_debug"
version = "${version}"
displayName = "Advanced Debug"
#updateJSONURL="http://myurl.me/"
displayURL = "https://github.com/Ultreon/advanced-debug"
logoFile="advanced_debug.png"
credits = "Qboi"
authors = "Ultreon Team"
description = """
${description}
"""
displayTest = "IGNORE_ALL_VERSION"

# Dependencies for the main mod.
[[dependencies.advanced_debug]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.advanced_debug]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},1.20.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.advanced_debug]]
modId = "architectury"
mandatory = true
versionRange = "[9.1,10)"
ordering = "NONE"
side = "CLIENT"
