modLoader = "javafml"
loaderVersion = "[2,)"
license = "Ultreon API 1.0"
issueTrackerURL = "https://github.com/Ultreon/advanced-debug/issues"

# The main mod, and all sub-mods.
[[mods]]
modId = "advanced_debug"
version = "${version}"
displayName = "Advanced Debug"
#updateJSONURL="http://myurl.me/"
displayURL = "https://github.com/Ultreon/advanced-debug"
logoFile="advanced_debug.png"
credits = "Qboi"
authors = "Ultreon Team"
description = """
${description}
"""
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "advanced-debug.mixins.json"

[[mixins]]
config = "advanced-debug-common.mixins.json"

# Dependencies for the main mod.
[[dependencies.advanced_debug]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.advanced_debug]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersion}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.advanced_debug]]
modId = "architectury"
type = "required"
versionRange = "[11,12)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.advanced_debug]]
modId = "ultreonlib"
type = "required"
versionRange = "[1.5,)"
ordering = "BEFORE"
side = "CLIENT"
