modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3.0"

# The main mod, and all sub-mods.
[[mods]]
modId = "advanced_debug_forge"
version = "0.0.0"
displayName = "(Wrapper) Advanced Debug"
description = '''
Forge wrapper for advanced debug
'''
itemIcon = "minecraft:string"
